version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql_container
    restart: "no"
    #changed from always to no
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
    ports:
      - "33066:3306"
  adminer:
    image: adminer
    container_name: adminer_container
    restart: "no"
    #changed from always to no
    ports:
      - 8080:8080